# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azurepipeline-test'
    subscriptionId: '873c007a-eeea-4460-9df3-0a8d528a316d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'NetworkWatcherRG'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    csmFile: 'https://github.com/Rajaniraji/DevOpasclassMay-Repo1-.git'
    deploymentMode: 'Incremental'
    deploymentName: 'pipelinetemplate'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
